aliases:
  - &environment
      docker:
        - image: circleci/android:api-28-alpha
      environment:
        JVM_OPTS: -Xmx3200m
  - &workspace
      attach_workspace:
        at: ~/code
      working_directory: ~/code

  - &tests
    - "Lint"
    - "Checkstyle"
    - "PMD"
    - "FindBugs"

version: 2
workflows:
  version: 2
  build_test_deploy:
    jobs:
      - "Dependencies"
      - "Lint":
          requires:
            - "Dependencies"
      - "Checkstyle":
          requires:
            - "Dependencies"
      - "PMD":
          requires:
            - "Dependencies"
      - "FindBugs":
          requires:
            - "Dependencies"
      - "Build":
          requires: *tests
      - "Deploy":
          requires:
            - "Build"
jobs:
  "Dependencies":
    <<: *environment
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          command: sudo chmod +x ./gradlew
      - run:
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - persist_to_workspace:
          root: workspace

  "Lint":
    <<: *environment
    <<: *workspace
    steps:
      - run:
          command: ./gradlew lint test
      - store_artifacts:
          path: app/build/reports
          destination: lint
      - store_test_results:
          path: app/build/test-results
          destination: lint

  "Checkstyle":
    <<: *environment
    <<: *workspace
    steps:
      - run:
          command: ./gradlew checkstyle
      - store_artifacts: # for display in Artifacts: https://circleci.com/docs/2.0/artifacts/
          path: app/build/reports
          destination: checkstyle
      - store_test_results: # for display in Test Summary: https://circleci.com/docs/2.0/collect-test-data/
          path: app/build/test-results
          destination: checkstyle

  "PMD":
    <<: *environment
    <<: *workspace
    steps:
      - run:
          command: ./gradlew pmd
      - store_artifacts: # for display in Artifacts: https://circleci.com/docs/2.0/artifacts/
          path: app/build/reports
          destination: pmd
      - store_test_results: # for display in Test Summary: https://circleci.com/docs/2.0/collect-test-data/
          path: app/build/test-results
          destination: pmd

  "FindBugs":
    <<: *environment
    <<: *workspace
    steps:
      - run:
          command: ./gradlew findbugs
      - store_artifacts: # for display in Artifacts: https://circleci.com/docs/2.0/artifacts/
          path: app/build/reports
          destination: findbugs
      - store_test_results: # for display in Test Summary: https://circleci.com/docs/2.0/collect-test-data/
          path: app/build/test-results
          destination: findbugs

  "Build":
    <<: *environment
    <<: *workspace
    steps:
      - run:
          command: ./gradlew assembleRelease
      - store_artifacts: # for display in Artifacts: https://circleci.com/docs/2.0/artifacts/
          path: app/build/outputs/apk
          destination: release

  "Deploy":
    <<: *environment
    <<: *workspace
    steps:
      - run:
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              bash ./scripts/deploy-fabric.sh
            fi
            if [ "${CIRCLE_BRANCH}" == "develop" ]; then
              bash ./scripts/deploy-appcenter.sh
            fi